### ISSUE TITLE
UFOLibError on write due to public.glyphOrder using unicode rather than utf-8

### ISSUE THREAD

**Issue by jvgaultney** [googlei18n/glyphsLib#241] opened 2017-10-19 14:16 UTC
When glyphsLib reads glyphOrder it then seems to store that data as unicode rather than utf-8. This makes ufo.lib fail to write public.glyphOrder: "ufoLib.UFOLibError: public.glyphOrder is not properly formatted." Was not a problem <2.0.0.dev0. I can work around the problem with this routine, though  it only illustrates the problem, and is not intended as a patch:

        neworder = []
        for name in ufo.lib["public.glyphOrder"]:
            neworder.append(name.encode('utf8'))

**Comment by anthrotype** [comment] 2017-10-19 14:21
I'd say this is not a bug, but rather a feature.
The glyph names in public.glyphOrder are text, not binary data. It makes sense for them to read as `unicode` type in python 2, which is the same as `str` type in python 3.
If you want UTF-8 bytes, you encode them with the respective encoding, like you do in the example snippet.

**Comment by anthrotype** [comment] 2017-10-19 14:22
oh wait.. you're saying ufoLib raises an error? That's ufoLib's bug if it does not accept a glyphOrder list of unicode strings..

Can you paste the full traceback?

**Comment by jvgaultney** [comment] 2017-10-19 14:26
Unless it's utf-8 ufiLib complains (from what I can tell). Traceback (we wrap calls to glyphsLib within our own psfglyphs2ufo script):

```
Traceback (most recent call last):
  File "/usr/local/bin/psfglyphs2ufo", line 9, in <module>
    load_entry_point('pysilfont==1.1.3', 'console_scripts', 'psfglyphs2ufo')()
  File "build/bdist.macosx-10.12-intel/egg/silfont/scripts/psfglyphs2ufo.py", line 21, in cmd
  File "build/bdist.macosx-10.12-intel/egg/silfont/core.py", line 505, in execute
  File "build/bdist.macosx-10.12-intel/egg/silfont/scripts/psfglyphs2ufo.py", line 19, in doit
  File "/Tools/glyphsLib/Lib/glyphsLib/__init__.py", line 103, in build_masters
    write_ufo(ufo, master_dir)
  File "/Tools/glyphsLib/Lib/glyphsLib/util.py", line 41, in write_ufo
    ufo.save(out_path)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 744, in save
    self._saveLib(writer=writer, saveAs=saveAs, progressBar=progressBar)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 838, in _saveLib
    self.saveLib(writer)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 855, in saveLib
    writer.writeLib(libCopy)
  File "/Library/Python/2.7/site-packages/ufoLib/__init__.py", line 935, in writeLib
    raise UFOLibError(message)
ufoLib.UFOLibError: public.glyphOrder is not properly formatted.
```

**Comment by anthrotype** [comment] 2017-10-19 14:38
ouch. i prefer to fix that over at ufoLib, thanks.

**Comment by anthrotype** [comment] 2017-10-20 08:24
it turns out this is the same issue as #236, which should be fixed now. Closing

**Closed by anthrotype** 2017-10-20 08:24 UTC
