### ISSUE TITLE
'infinity' being interpreted as <real> when building lib.plist

### ISSUE THREAD

**Issue by jvgaultney** [googlei18n/glyphsLib#236] opened 2017-10-18 13:44 UTC
When using build_masters() in v2.0.0.dev0 the value 'infinity' is being written incorrectly in UFOs. For example, the following in a .glyphs file:

```
public.postscriptNames = {
Infinity = infinity;
};

```
Is being output as

```
		<key>public.postscriptNames</key>
		<dict>
			<key>Infinity</key>
			<real>inf</real>
		</dict>

```
rather than

```
		<key>public.postscriptNames</key>
		<dict>
			<key>Infinity</key>
			<string>infinity</string>
		</dict>

```

**Comment by jvgaultney** [comment] 2017-10-18 13:44
This problem is not present in v1.8

**Comment by anthrotype** [comment] 2017-10-18 13:47
this is definitely a bug, thanks for the report!

**Comment by belluzj** [comment] 2017-10-19 12:59
@anthrotype Should I look into this issue as well?

**Comment by anthrotype** [comment] 2017-10-19 13:07
If you can, yes, thank you

**Comment by belluzj** [comment] 2017-10-19 14:06
@jvgaultney I can't reproduce. Would you mind sharing your input Glyphs file, or at least more context about the "public.postscriptNames" key? Is it in a userData, or customParameters?

**Comment by anthrotype** [comment] 2017-10-19 14:11
i think (but haven't tried myself) that it is originally in a UFO lib.plist, which is then imported in Glyphs.app via the native UFO import feature, then the glyphs file was saved and Victor attempted to export it back to UFO with glyphsLib. 
 
According to what he says in https://github.com/googlei18n/glyphsLib/issues/230, it appears that upon importing UFOs, Glyphs.app temporarily moves private values in the lib.plist to the userData, and upon exporting it restores them in the UFO lib (but glyphsLib doesn't do that.. yet?).

**Comment by belluzj** [comment] 2017-10-19 14:27
> but glyphsLib doesn't do that.. yet?

It should definitely do something of the sort for the roundtrip.

As for this particular issue, there is already this parser test:

```
    def test_parse_str_infinity(self):
        self.run_test(
            b'{mystr = infinity;}',
            [('mystr', 'infinity')]
        )
```

and I tried to add a builder test:

```
    def test_infinity_as_string(self):
        # https://github.com/googlei18n/glyphsLib/issues/236
        font = generate_minimal_font()
        font.userData['public.postscriptNames'] = {'Infinity': 'infinity'}
        ufo = to_ufos(font)[0]
        self.assertEqual(
            'infinity',
            ufo.lib['public.postscriptNames']['Infinity']
        )
        from glyphsLib.util import write_ufo
        write_ufo(ufo, '.')
```

but both are green and the written value is a string. So I guess that the problem only happens with the specific file that @jvgaultney has tested, for reasons more obscure than what I'm able to imagine on my own :)

**Comment by jvgaultney** [comment] 2017-10-19 14:36
This seems to have been fixed, probably in pull request #227 although other problems introduced in that request kept me from verifying this fix until I'd worked around them.

**Comment by anthrotype** [comment] 2017-10-19 14:39
excellent, so can we close this?

**Comment by jvgaultney** [comment] 2017-10-19 14:40
Yes

**Comment by belluzj** [comment] 2017-10-19 14:41
> other problems introduced in that request kept me from verifying this fix until I'd worked around them

Please open other issues for those

**Closed by belluzj** 2017-10-19 14:41 UTC
Labels: bug

**Comment by jvgaultney** [comment] 2017-10-19 14:44
I did a little while ago #241 , though it seems I need to report that as an issue in ufoLib

**Comment by belluzj** [comment] 2017-10-19 14:46
Thanks :)
