### ISSUE TITLE
UFOFormat field should not be in lib.plist

### ISSUE THREAD

**Issue by DavidRaymond** [googlei18n/glyphsLib#266] opened 2017-11-02 14:39 UTC
UFOFormat is not a valid lib.plist key.  

Although in the userData section of the .glyphs file, it is not in the UFOlib within userData, and that is where lib.list fields are stored.

I don't think there is any need to transfer the value of that UFOFormat to anywhere within the UFO.

**Comment by schriftgestalt** [comment] 2017-11-02 20:54
This value is stored in the .glyphs file to know that the data comes from and .ufo of that format and to save it back in that format.

**Comment by anthrotype** [comment] 2017-11-02 21:22
Technically there aren’t “invalid lib.plist keys” provided they are prefixed with some reverse domain notation. But I see the point that it may be redundant. GlyphsLib currently always exports to UFO3, although defcon could export to UFO2 as well.

**Comment by DavidRaymond** [comment] 2017-11-02 21:26
Agreed it could be made valid by adding a prefix, but it is redundant within the UFO.  The value held within the .glyphs file could be used if, in the future,  support for UFO2 export was added to glyphsLib.

**Comment by schriftgestalt** [comment] 2017-11-02 21:28
I might be good to store it some where for round tripping reasons. But that might not be important.

**Comment by anthrotype** [comment] 2017-11-02 21:29
who is exporting that key, glyphsLib or Glyphs.app?

**Comment by DavidRaymond** [comment] 2017-11-02 21:32
In my tests I'm only using glyphsLib, so that must be taking it from the .glyphs file and writing it to the UFO.

**Comment by anthrotype** [comment] 2017-11-02 21:39
Looks to me related to https://github.com/googlei18n/glyphsLib/issues/230

**Comment by anthrotype** [comment] 2018-09-18 18:18
duplicate of #230

**Closed by anthrotype** 2018-09-18 18:18 UTC
