### ISSUE TITLE
Skip empty Axes

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#281] opened 2017-11-08 10:27 UTC
If the calculated mapping for an axis has a length of zero (e.g. `'map': {0.0: 0.0},` or 'map': {72.0: 72.0},) scrip the axis.

**Comment by anthrotype** [comment] 2017-11-08 10:44
duplicate of https://github.com/googlei18n/glyphsLib/issues/178

**Closed by anthrotype** 2017-11-08 10:44 UTC
